install:
  - cinst pester

build: false

install:
  - ps: mkdir c:\deploy
  - ps: Write-Output 'Deploy completed'
  
test_script:
  - ps: if (-not (Test-Path c:\deploy)) { Write-Error "Test path not found" }
  - ps: if (-not (Test-Path c:\deploy2)) { Write-Error "Test path not found" }
