build: false

install:
  - cinst pester
  - ps: mkdir c:\deploy
  - ps: mkdir c:\deploy3

test_script:
  - ps: if (-not (Test-Path c:\deploy)) {exit 1}
  - ps: if (-not (Test-Path c:\deploy2)) {exit 1}
